// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AssetHub.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAssetCopyright : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Copyright",
                table: "Assets",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "idx_shares_created_by_user_id",
                table: "Shares",
                column: "CreatedByUserId");

            migrationBuilder.CreateIndex(
                name: "idx_shares_expires_at",
                table: "Shares",
                column: "ExpiresAt");

            migrationBuilder.CreateIndex(
                name: "idx_collection_acl_unique",
                table: "CollectionAcls",
                columns: new[] { "CollectionId", "PrincipalType", "PrincipalId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "idx_audit_target_id",
                table: "AuditEvents",
                column: "TargetId");

            migrationBuilder.CreateIndex(
                name: "idx_assets_created_by_user_id",
                table: "Assets",
                column: "CreatedByUserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "idx_shares_created_by_user_id",
                table: "Shares");

            migrationBuilder.DropIndex(
                name: "idx_shares_expires_at",
                table: "Shares");

            migrationBuilder.DropIndex(
                name: "idx_collection_acl_unique",
                table: "CollectionAcls");

            migrationBuilder.DropIndex(
                name: "idx_audit_target_id",
                table: "AuditEvents");

            migrationBuilder.DropIndex(
                name: "idx_assets_created_by_user_id",
                table: "Assets");

            migrationBuilder.DropColumn(
                name: "Copyright",
                table: "Assets");
        }
    }
}
