// <auto-generated />
using System;
using System.Collections.Generic;
using AssetHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace AssetHub.Infrastructure.Migrations
{
    [DbContext(typeof(AssetHubDbContext))]
    [Migration("20260426185612_AddCollectionParentIdAndInheritFlag")]
    partial class AddCollectionParentIdAndInheritFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetHub.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Copyright")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EditDocument")
                        .HasColumnType("jsonb");

                    b.Property<string>("MediumObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PosterObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ThumbObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WorkflowStateUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("idx_assets_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_assets_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_assets_created_by_user_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_assets_deleted_at")
                        .HasFilter("\"DeletedAt\" IS NOT NULL");

                    b.HasIndex("OriginalObjectKey")
                        .HasDatabaseName("idx_assets_original_object_key");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_asset_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("SourceAssetId")
                        .HasDatabaseName("idx_assets_source_asset_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_assets_status");

                    b.HasIndex("WorkflowState")
                        .HasDatabaseName("idx_assets_workflow_state");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AddedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("idx_asset_collection_collection_id");

                    b.HasIndex("AssetId", "CollectionId")
                        .IsUnique()
                        .HasDatabaseName("idx_asset_collection_unique");

                    b.ToTable("AssetCollections");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("MentionedUserIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("idx_asset_comment_parent");

                    b.HasIndex("AssetId", "CreatedAt")
                        .HasDatabaseName("idx_asset_comment_asset_created");

                    b.ToTable("AssetComments");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetMetadataValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetadataFieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ValueTaxonomyTermId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("idx_asset_metadata_values_asset");

                    b.HasIndex("ValueTaxonomyTermId")
                        .HasDatabaseName("idx_asset_metadata_values_taxonomy_term")
                        .HasFilter("\"ValueTaxonomyTermId\" IS NOT NULL");

                    b.HasIndex("MetadataFieldId", "AssetId")
                        .HasDatabaseName("idx_asset_metadata_values_field_asset");

                    b.ToTable("AssetMetadataValues");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EditDocument")
                        .HasColumnType("jsonb");

                    b.Property<string>("MediumObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetadataSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PosterObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_asset_version_asset_version_unique");

                    b.ToTable("AssetVersions");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetWorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CreatedAt")
                        .HasDatabaseName("idx_asset_workflow_transition_asset_created");

                    b.ToTable("AssetWorkflowTransitions");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_created_at");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("idx_audit_target_id");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("idx_audit_event_type_created");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("idx_brand_default")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("InheritParentAcl")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentCollectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("idx_collections_brand_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_collections_name_unique");

                    b.HasIndex("ParentCollectionId")
                        .HasDatabaseName("idx_collections_parent_id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.CollectionAcl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("idx_collection_acl_collection_id");

                    b.HasIndex("PrincipalType", "PrincipalId")
                        .HasDatabaseName("idx_collection_acl_principal");

                    b.HasIndex("CollectionId", "PrincipalType", "PrincipalId")
                        .IsUnique()
                        .HasDatabaseName("idx_collection_acl_unique");

                    b.ToTable("CollectionAcls");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.ExportPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FitMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_export_presets_name_unique");

                    b.ToTable("ExportPresets");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.GuestInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcceptedUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<List<Guid>>("CollectionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_guest_invitation_token_hash_unique");

                    b.HasIndex("ExpiresAt", "RevokedAt")
                        .HasDatabaseName("idx_guest_invitation_expiry_revoked");

                    b.ToTable("GuestInvitations");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MetadataField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Facetable")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LabelSv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<Guid>("MetadataSchemaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NumericMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NumericMin")
                        .HasColumnType("numeric");

                    b.Property<string>("PatternRegex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("Searchable")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("SelectOptions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaxonomyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaxonomyId");

                    b.HasIndex("MetadataSchemaId", "Key")
                        .IsUnique()
                        .HasDatabaseName("idx_metadata_fields_schema_key_unique");

                    b.HasIndex("MetadataSchemaId", "SortOrder")
                        .HasDatabaseName("idx_metadata_fields_schema_sort");

                    b.ToTable("MetadataFields");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MetadataSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("idx_metadata_schemas_collection_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_metadata_schemas_name_unique");

                    b.HasIndex("Scope")
                        .HasDatabaseName("idx_metadata_schemas_scope");

                    b.ToTable("MetadataSchemas");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Migration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("DefaultCollectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldMapping")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSucceeded")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_migrations_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_migrations_status");

                    b.ToTable("Migrations");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MigrationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("CollectionNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Copyright")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsFileStaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("MigrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_migration_items_idempotency_unique");

                    b.HasIndex("MigrationId", "RowNumber")
                        .HasDatabaseName("idx_migration_items_migration_row");

                    b.HasIndex("MigrationId", "Status")
                        .HasDatabaseName("idx_migration_items_migration_status");

                    b.ToTable("MigrationItems");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_notifications_user_created");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("idx_notifications_user_read");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.NotificationPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnsubscribeTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UnsubscribeTokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_notif_prefs_unsubscribe_hash_unique");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_notif_prefs_user_unique");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.OrphanedObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptCount", "CreatedAt")
                        .HasDatabaseName("idx_orphaned_object_attempts_created");

                    b.ToTable("OrphanedObjects");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.PersonalAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_pat_token_hash_unique");

                    b.HasIndex("OwnerUserId", "CreatedAt")
                        .HasDatabaseName("idx_pat_owner_created");

                    b.ToTable("PersonalAccessTokens");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastHighestSeenAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notify")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("idx_saved_searches_owner");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("idx_saved_searches_owner_name_unique");

                    b.ToTable("SavedSearches");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordEncrypted")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PasswordVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenEncrypted")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_shares_created_by_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_shares_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_shares_token_hash_unique");

                    b.HasIndex("ScopeType", "ScopeId")
                        .HasDatabaseName("idx_shares_scope");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Taxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_taxonomies_name_unique");

                    b.ToTable("Taxonomies");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.TaxonomyTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LabelSv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentTermId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaxonomyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentTermId")
                        .HasDatabaseName("idx_taxonomy_terms_parent");

                    b.HasIndex("TaxonomyId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_taxonomy_terms_taxonomy_slug_unique");

                    b.HasIndex("TaxonomyId", "SortOrder")
                        .HasDatabaseName("idx_taxonomy_terms_taxonomy_sort");

                    b.ToTable("TaxonomyTerms");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<List<string>>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_webhook_active");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_webhook_delivery_status");

                    b.HasIndex("WebhookId", "CreatedAt")
                        .HasDatabaseName("idx_webhook_delivery_webhook_created");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.ZipDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RequestedByUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShareTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ZipFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ZipObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_zip_downloads_expires_at");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("idx_zip_downloads_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_zip_downloads_status");

                    b.ToTable("ZipDownloads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Asset", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "SourceAsset")
                        .WithMany("Derivatives")
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceAsset");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetCollection", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetCollections")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Entities.Collection", "Collection")
                        .WithMany("AssetCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetComment", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Entities.AssetComment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Asset");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetMetadataValue", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Entities.MetadataField", "MetadataField")
                        .WithMany()
                        .HasForeignKey("MetadataFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Entities.TaxonomyTerm", "ValueTaxonomyTerm")
                        .WithMany()
                        .HasForeignKey("ValueTaxonomyTermId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("MetadataField");

                    b.Navigation("ValueTaxonomyTerm");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetVersion", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "Asset")
                        .WithMany("Versions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.AssetWorkflowTransition", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Collection", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetHub.Domain.Entities.Collection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.CollectionAcl", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Collection", "Collection")
                        .WithMany("Acls")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MetadataField", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.MetadataSchema", "MetadataSchema")
                        .WithMany("Fields")
                        .HasForeignKey("MetadataSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetHub.Domain.Entities.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MetadataSchema");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MetadataSchema", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MigrationItem", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Migration", "Migration")
                        .WithMany("Items")
                        .HasForeignKey("MigrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.TaxonomyTerm", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.TaxonomyTerm", "ParentTerm")
                        .WithMany("Children")
                        .HasForeignKey("ParentTermId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AssetHub.Domain.Entities.Taxonomy", "Taxonomy")
                        .WithMany("Terms")
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTerm");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("AssetHub.Domain.Entities.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetCollections");

                    b.Navigation("Derivatives");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Acls");

                    b.Navigation("AssetCollections");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.MetadataSchema", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Migration", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.Taxonomy", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("AssetHub.Domain.Entities.TaxonomyTerm", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
